// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

var greeting = "Good morning";

function greetUser(name) {
  return greeting + name;
}

function greetUserEvening(name) {
  return "Good evening, " + (String(name) + "");
}

exports.greeting = greeting;
exports.greetUser = greetUser;
exports.greetUserEvening = greetUserEvening;
/*  Not a pure module */
